databases:
  - name: instaclone-db
    databaseName: instaclone
    user: instaclone
    plan: free

services:
  - type: web
    name: instaclone
    runtime: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --no-input &&
      python manage.py migrate --no-input &&
      python manage.py create_demo_user
    startCommand: gunicorn instagram_clone.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: instaclone-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.7"
